server:
  port: 8501
spring:
  application:
    name: wmcloud-broker-server
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-2zed7zks90z1y1p2apo.mysql.rds.aliyuncs.com:3306/wm?useSSL=true
    username: wmadmin
    password: Wmadmin123


eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
  client:
    registryFetchIntervalSeconds: 5
    service-url:
      defaultZone: http://localhost:8001/eureka/
management:
  metrics:
    web:
      server:
        auto-time-requests: false
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
